# Generated by Django 4.0.4 on 2023-01-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_register_age_register_dob_register_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='branch',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
