# Generated by Django 4.1.5 on 2023-02-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_register_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_name', models.CharField(max_length=20)),
                ('book_author', models.CharField(max_length=15)),
                ('publication_date', models.DateField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
